---
version: '2.0'
networks:
  demo:
services:
  influxdb:
    image: influxdb
    networks:
      - demo

  grafana:
    image: "grafana/grafana"
    networks:
      - demo
    ports:
      - "80:3000"

  feeder:
    build:
      context: "./feeder"
    image: "feeder"
    networks:
      - demo
